### ISSUE TITLE
错别字修改

### ISSUE THREAD

**Issue by LiYaoheng** [penglongli/My-Resume#1]
readme中这一行：
>  less目录存储的文件时源文件  

中的**时**修改为**是**   
是这样吗？ :smile:

**Comment by penglongli** [comment]
感谢提醒，已Fix :) https://github.com/penglongli/My-Resume/commit/3e881b95274dcd5b6f912e25d457e3f9c8013c7e

**Comment by LiYaoheng** [comment]
哈哈，感谢分享 👍
