### ISSUE TITLE
简历上的个人网站被重定向到非法网站了

### ISSUE THREAD

**Issue by zo-ly** [penglongli/My-Resume#2]
因为没找到邮箱或者其他联系方式，只能开个issue提醒一下了= _ =

**Comment by penglongli** [comment]
感谢提醒，我这边看到的是正常的。
可能是你的流量，被当前的运营商劫持了

**Comment by zo-ly** [comment]
http://penglongli.github.io/My-Resume/ 上的个人网站是这个 http://www.pelinli.com/

确实是有问题的

**Comment by penglongli** [comment]
> http://penglongli.github.io/My-Resume/ 上的个人网站是这个 http://www.pelinli.com/
> 
> 确实是有问题的

啊，我理解你意思了。这个域名已没在我下边了，我晚上提交下把这个屏蔽了

感谢~
